apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bookstore-kustomize
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: bookstore-api
  interval: 30m
  retryInterval: 5m
  path: ./kusomize
  prune: true
  wait: true
  timeout: 2m
