apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: database
  labels:
    app: bookstore
data:
  POSTGRES_DB: bookstore
  POSTGRES_USER: santosh
  POSTGRES_PASSWORD: dts123
  POSTGRES_HOST: postgres-0.postgres.database.svc.cluster.local:5432 
  POSTGRES_PORT: "5432"
  sslmode: disable
  

